version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-rh
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=banco123
      - POSTGRES_DB=evolution_db
    ports:
      - "5433:5432" # Porta 5433 para acesso externo (DBeaver)
    volumes:
      - postgres_data_novo:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - rh-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-rh
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=evolution_db
      - DB_POSTGRESDB_USER=postgres
      - DB_POSTGRESDB_PASSWORD=banco123
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PERSONALIZATION_ENABLED=false
      - N8N_TELEMETRY_ENABLED=false
      
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - rh-network
    depends_on:
      - db

  evolution:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=apikeyjannotti
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:banco123@db:5432/evolution_db?sslmode=disable
    networks:
      - rh-network
    depends_on:
      - db

networks:
  rh-network:
    driver: bridge

volumes:
  postgres_data_novo: