version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-rh
    restart: always
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: n8n_password
      POSTGRES_DB: n8n_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - rh-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-rh
    restart: always
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n_db
      - DB_POSTGRESDB_USER=n8n_user
      - DB_POSTGRESDB_PASSWORD=n8n_password
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - rh-network
    depends_on:
      - db

  evolution:
    image: atendai/evolution-api:latest
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=http://localhost:8080
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=sua_chave_global_aqui
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      # MUDAMOS O FINAL PARA evolution_db
      - DATABASE_CONNECTION_URI=postgresql://n8n_user:n8n_password@db:5432/evolution_db?sslmode=disable
    networks:
      - rh-network
    depends_on:
      - db

networks:
  rh-network:
    driver: bridge